//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18052 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.CarChannel.Common.com.bitauto.das {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DasSoap", Namespace="http://www.bitauto.com/")]
    public partial class Das : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAllNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumberByDealerIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNumberByDealerStringOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePassOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Das() {
            this.Url = global::BitAuto.CarChannel.Common.Properties.Settings.Default.Common_com_bitauto_das_NumberFormat;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAllNumberCompletedEventHandler GetAllNumberCompleted;
        
        /// <remarks/>
        public event GetNumberByDealerIDCompletedEventHandler GetNumberByDealerIDCompleted;
        
        /// <remarks/>
        public event GetNumberByDealerStringCompletedEventHandler GetNumberByDealerStringCompleted;
        
        /// <remarks/>
        public event UpdatePassCompletedEventHandler UpdatePassCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bitauto.com/GetAllNumber", RequestNamespace="http://www.bitauto.com/", ResponseNamespace="http://www.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetAllNumber() {
            object[] results = this.Invoke("GetAllNumber", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllNumberAsync() {
            this.GetAllNumberAsync(null);
        }
        
        /// <remarks/>
        public void GetAllNumberAsync(object userState) {
            if ((this.GetAllNumberOperationCompleted == null)) {
                this.GetAllNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllNumberOperationCompleted);
            }
            this.InvokeAsync("GetAllNumber", new object[0], this.GetAllNumberOperationCompleted, userState);
        }
        
        private void OnGetAllNumberOperationCompleted(object arg) {
            if ((this.GetAllNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllNumberCompleted(this, new GetAllNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bitauto.com/GetNumberByDealerID", RequestNamespace="http://www.bitauto.com/", ResponseNamespace="http://www.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetNumberByDealerID(int DealerID) {
            object[] results = this.Invoke("GetNumberByDealerID", new object[] {
                        DealerID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumberByDealerIDAsync(int DealerID) {
            this.GetNumberByDealerIDAsync(DealerID, null);
        }
        
        /// <remarks/>
        public void GetNumberByDealerIDAsync(int DealerID, object userState) {
            if ((this.GetNumberByDealerIDOperationCompleted == null)) {
                this.GetNumberByDealerIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumberByDealerIDOperationCompleted);
            }
            this.InvokeAsync("GetNumberByDealerID", new object[] {
                        DealerID}, this.GetNumberByDealerIDOperationCompleted, userState);
        }
        
        private void OnGetNumberByDealerIDOperationCompleted(object arg) {
            if ((this.GetNumberByDealerIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumberByDealerIDCompleted(this, new GetNumberByDealerIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bitauto.com/GetNumberByDealerString", RequestNamespace="http://www.bitauto.com/", ResponseNamespace="http://www.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetNumberByDealerString(string DealerID) {
            object[] results = this.Invoke("GetNumberByDealerString", new object[] {
                        DealerID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetNumberByDealerStringAsync(string DealerID) {
            this.GetNumberByDealerStringAsync(DealerID, null);
        }
        
        /// <remarks/>
        public void GetNumberByDealerStringAsync(string DealerID, object userState) {
            if ((this.GetNumberByDealerStringOperationCompleted == null)) {
                this.GetNumberByDealerStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNumberByDealerStringOperationCompleted);
            }
            this.InvokeAsync("GetNumberByDealerString", new object[] {
                        DealerID}, this.GetNumberByDealerStringOperationCompleted, userState);
        }
        
        private void OnGetNumberByDealerStringOperationCompleted(object arg) {
            if ((this.GetNumberByDealerStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNumberByDealerStringCompleted(this, new GetNumberByDealerStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bitauto.com/UpdatePass", RequestNamespace="http://www.bitauto.com/", ResponseNamespace="http://www.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdatePass(int DealerID, string NewPass) {
            object[] results = this.Invoke("UpdatePass", new object[] {
                        DealerID,
                        NewPass});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePassAsync(int DealerID, string NewPass) {
            this.UpdatePassAsync(DealerID, NewPass, null);
        }
        
        /// <remarks/>
        public void UpdatePassAsync(int DealerID, string NewPass, object userState) {
            if ((this.UpdatePassOperationCompleted == null)) {
                this.UpdatePassOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePassOperationCompleted);
            }
            this.InvokeAsync("UpdatePass", new object[] {
                        DealerID,
                        NewPass}, this.UpdatePassOperationCompleted, userState);
        }
        
        private void OnUpdatePassOperationCompleted(object arg) {
            if ((this.UpdatePassCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePassCompleted(this, new UpdatePassCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllNumberCompletedEventHandler(object sender, GetAllNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetNumberByDealerIDCompletedEventHandler(object sender, GetNumberByDealerIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumberByDealerIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumberByDealerIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetNumberByDealerStringCompletedEventHandler(object sender, GetNumberByDealerStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNumberByDealerStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNumberByDealerStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdatePassCompletedEventHandler(object sender, UpdatePassCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePassCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePassCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591