//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18052 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.CarChannel.BLL.Das {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GroupServiceSoap", Namespace="http://tempuri.org/")]
    public partial class GroupService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private DasSoapHeader dasSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetLatestOrderUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveGroupPurchaseListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveGroupPurchasePageListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveGroupPurchaseByCityAndSerialOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveGroupPurchaseTopListByCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetHistoryGroupPurchaseListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupPurchaseInforOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPriorGroupPurchaseInforOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCityListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarSerialListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarSerialListTopOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddGoupSignUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupCarsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastGroupCarsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCityNewGroupPurchaseListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCityListByCsIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarListByCsIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupPurchaseSearchConditionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGroupPurchaseSearchContentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetActiveGroupPurchaseTopListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GroupService() {
            this.Url = global::BitAuto.CarChannel.BLL.Properties.Settings.Default.BLL_Das_GroupService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public DasSoapHeader DasSoapHeaderValue {
            get {
                return this.dasSoapHeaderValueField;
            }
            set {
                this.dasSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLatestOrderUserCompletedEventHandler GetLatestOrderUserCompleted;
        
        /// <remarks/>
        public event GetActiveGroupPurchaseListCompletedEventHandler GetActiveGroupPurchaseListCompleted;
        
        /// <remarks/>
        public event GetActiveGroupPurchasePageListCompletedEventHandler GetActiveGroupPurchasePageListCompleted;
        
        /// <remarks/>
        public event GetActiveGroupPurchaseByCityAndSerialCompletedEventHandler GetActiveGroupPurchaseByCityAndSerialCompleted;
        
        /// <remarks/>
        public event GetActiveGroupPurchaseTopListByCityCompletedEventHandler GetActiveGroupPurchaseTopListByCityCompleted;
        
        /// <remarks/>
        public event GetHistoryGroupPurchaseListCompletedEventHandler GetHistoryGroupPurchaseListCompleted;
        
        /// <remarks/>
        public event GetGroupPurchaseInforCompletedEventHandler GetGroupPurchaseInforCompleted;
        
        /// <remarks/>
        public event GetPriorGroupPurchaseInforCompletedEventHandler GetPriorGroupPurchaseInforCompleted;
        
        /// <remarks/>
        public event GetCityListCompletedEventHandler GetCityListCompleted;
        
        /// <remarks/>
        public event GetCarSerialListCompletedEventHandler GetCarSerialListCompleted;
        
        /// <remarks/>
        public event GetCarSerialListTopCompletedEventHandler GetCarSerialListTopCompleted;
        
        /// <remarks/>
        public event AddGoupSignUpCompletedEventHandler AddGoupSignUpCompleted;
        
        /// <remarks/>
        public event GetGroupCarsListCompletedEventHandler GetGroupCarsListCompleted;
        
        /// <remarks/>
        public event GetLastGroupCarsListCompletedEventHandler GetLastGroupCarsListCompleted;
        
        /// <remarks/>
        public event GetCityNewGroupPurchaseListCompletedEventHandler GetCityNewGroupPurchaseListCompleted;
        
        /// <remarks/>
        public event GetCityListByCsIDCompletedEventHandler GetCityListByCsIDCompleted;
        
        /// <remarks/>
        public event GetCarListByCsIDCompletedEventHandler GetCarListByCsIDCompleted;
        
        /// <remarks/>
        public event GetGroupPurchaseSearchConditionCompletedEventHandler GetGroupPurchaseSearchConditionCompleted;
        
        /// <remarks/>
        public event GetGroupPurchaseSearchContentCompletedEventHandler GetGroupPurchaseSearchContentCompleted;
        
        /// <remarks/>
        public event GetActiveGroupPurchaseTopListCompletedEventHandler GetActiveGroupPurchaseTopListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLatestOrderUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLatestOrderUser(int GroupID, int RowCount) {
            object[] results = this.Invoke("GetLatestOrderUser", new object[] {
                        GroupID,
                        RowCount});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetLatestOrderUserAsync(int GroupID, int RowCount) {
            this.GetLatestOrderUserAsync(GroupID, RowCount, null);
        }
        
        /// <remarks/>
        public void GetLatestOrderUserAsync(int GroupID, int RowCount, object userState) {
            if ((this.GetLatestOrderUserOperationCompleted == null)) {
                this.GetLatestOrderUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLatestOrderUserOperationCompleted);
            }
            this.InvokeAsync("GetLatestOrderUser", new object[] {
                        GroupID,
                        RowCount}, this.GetLatestOrderUserOperationCompleted, userState);
        }
        
        private void OnGetLatestOrderUserOperationCompleted(object arg) {
            if ((this.GetLatestOrderUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLatestOrderUserCompleted(this, new GetLatestOrderUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActiveGroupPurchaseList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetActiveGroupPurchaseList(int CityID) {
            object[] results = this.Invoke("GetActiveGroupPurchaseList", new object[] {
                        CityID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchaseListAsync(int CityID) {
            this.GetActiveGroupPurchaseListAsync(CityID, null);
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchaseListAsync(int CityID, object userState) {
            if ((this.GetActiveGroupPurchaseListOperationCompleted == null)) {
                this.GetActiveGroupPurchaseListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveGroupPurchaseListOperationCompleted);
            }
            this.InvokeAsync("GetActiveGroupPurchaseList", new object[] {
                        CityID}, this.GetActiveGroupPurchaseListOperationCompleted, userState);
        }
        
        private void OnGetActiveGroupPurchaseListOperationCompleted(object arg) {
            if ((this.GetActiveGroupPurchaseListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveGroupPurchaseListCompleted(this, new GetActiveGroupPurchaseListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActiveGroupPurchasePageList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetActiveGroupPurchasePageList(int PageSize, int PageIndex, int CityID) {
            object[] results = this.Invoke("GetActiveGroupPurchasePageList", new object[] {
                        PageSize,
                        PageIndex,
                        CityID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchasePageListAsync(int PageSize, int PageIndex, int CityID) {
            this.GetActiveGroupPurchasePageListAsync(PageSize, PageIndex, CityID, null);
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchasePageListAsync(int PageSize, int PageIndex, int CityID, object userState) {
            if ((this.GetActiveGroupPurchasePageListOperationCompleted == null)) {
                this.GetActiveGroupPurchasePageListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveGroupPurchasePageListOperationCompleted);
            }
            this.InvokeAsync("GetActiveGroupPurchasePageList", new object[] {
                        PageSize,
                        PageIndex,
                        CityID}, this.GetActiveGroupPurchasePageListOperationCompleted, userState);
        }
        
        private void OnGetActiveGroupPurchasePageListOperationCompleted(object arg) {
            if ((this.GetActiveGroupPurchasePageListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveGroupPurchasePageListCompleted(this, new GetActiveGroupPurchasePageListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActiveGroupPurchaseByCityAndSerial", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupPurchaseEntity GetActiveGroupPurchaseByCityAndSerial(int CityID, int SerialID) {
            object[] results = this.Invoke("GetActiveGroupPurchaseByCityAndSerial", new object[] {
                        CityID,
                        SerialID});
            return ((GroupPurchaseEntity)(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchaseByCityAndSerialAsync(int CityID, int SerialID) {
            this.GetActiveGroupPurchaseByCityAndSerialAsync(CityID, SerialID, null);
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchaseByCityAndSerialAsync(int CityID, int SerialID, object userState) {
            if ((this.GetActiveGroupPurchaseByCityAndSerialOperationCompleted == null)) {
                this.GetActiveGroupPurchaseByCityAndSerialOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveGroupPurchaseByCityAndSerialOperationCompleted);
            }
            this.InvokeAsync("GetActiveGroupPurchaseByCityAndSerial", new object[] {
                        CityID,
                        SerialID}, this.GetActiveGroupPurchaseByCityAndSerialOperationCompleted, userState);
        }
        
        private void OnGetActiveGroupPurchaseByCityAndSerialOperationCompleted(object arg) {
            if ((this.GetActiveGroupPurchaseByCityAndSerialCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveGroupPurchaseByCityAndSerialCompleted(this, new GetActiveGroupPurchaseByCityAndSerialCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActiveGroupPurchaseTopListByCity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetActiveGroupPurchaseTopListByCity(int CityID, int RowCount) {
            object[] results = this.Invoke("GetActiveGroupPurchaseTopListByCity", new object[] {
                        CityID,
                        RowCount});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchaseTopListByCityAsync(int CityID, int RowCount) {
            this.GetActiveGroupPurchaseTopListByCityAsync(CityID, RowCount, null);
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchaseTopListByCityAsync(int CityID, int RowCount, object userState) {
            if ((this.GetActiveGroupPurchaseTopListByCityOperationCompleted == null)) {
                this.GetActiveGroupPurchaseTopListByCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveGroupPurchaseTopListByCityOperationCompleted);
            }
            this.InvokeAsync("GetActiveGroupPurchaseTopListByCity", new object[] {
                        CityID,
                        RowCount}, this.GetActiveGroupPurchaseTopListByCityOperationCompleted, userState);
        }
        
        private void OnGetActiveGroupPurchaseTopListByCityOperationCompleted(object arg) {
            if ((this.GetActiveGroupPurchaseTopListByCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveGroupPurchaseTopListByCityCompleted(this, new GetActiveGroupPurchaseTopListByCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetHistoryGroupPurchaseList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetHistoryGroupPurchaseList(int CityID, int SerialID, int RowCount) {
            object[] results = this.Invoke("GetHistoryGroupPurchaseList", new object[] {
                        CityID,
                        SerialID,
                        RowCount});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetHistoryGroupPurchaseListAsync(int CityID, int SerialID, int RowCount) {
            this.GetHistoryGroupPurchaseListAsync(CityID, SerialID, RowCount, null);
        }
        
        /// <remarks/>
        public void GetHistoryGroupPurchaseListAsync(int CityID, int SerialID, int RowCount, object userState) {
            if ((this.GetHistoryGroupPurchaseListOperationCompleted == null)) {
                this.GetHistoryGroupPurchaseListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHistoryGroupPurchaseListOperationCompleted);
            }
            this.InvokeAsync("GetHistoryGroupPurchaseList", new object[] {
                        CityID,
                        SerialID,
                        RowCount}, this.GetHistoryGroupPurchaseListOperationCompleted, userState);
        }
        
        private void OnGetHistoryGroupPurchaseListOperationCompleted(object arg) {
            if ((this.GetHistoryGroupPurchaseListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHistoryGroupPurchaseListCompleted(this, new GetHistoryGroupPurchaseListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupPurchaseInfor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupPurchaseEntity GetGroupPurchaseInfor(int GroupID) {
            object[] results = this.Invoke("GetGroupPurchaseInfor", new object[] {
                        GroupID});
            return ((GroupPurchaseEntity)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupPurchaseInforAsync(int GroupID) {
            this.GetGroupPurchaseInforAsync(GroupID, null);
        }
        
        /// <remarks/>
        public void GetGroupPurchaseInforAsync(int GroupID, object userState) {
            if ((this.GetGroupPurchaseInforOperationCompleted == null)) {
                this.GetGroupPurchaseInforOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupPurchaseInforOperationCompleted);
            }
            this.InvokeAsync("GetGroupPurchaseInfor", new object[] {
                        GroupID}, this.GetGroupPurchaseInforOperationCompleted, userState);
        }
        
        private void OnGetGroupPurchaseInforOperationCompleted(object arg) {
            if ((this.GetGroupPurchaseInforCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupPurchaseInforCompleted(this, new GetGroupPurchaseInforCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPriorGroupPurchaseInfor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupPurchaseEntity GetPriorGroupPurchaseInfor(int GroupID) {
            object[] results = this.Invoke("GetPriorGroupPurchaseInfor", new object[] {
                        GroupID});
            return ((GroupPurchaseEntity)(results[0]));
        }
        
        /// <remarks/>
        public void GetPriorGroupPurchaseInforAsync(int GroupID) {
            this.GetPriorGroupPurchaseInforAsync(GroupID, null);
        }
        
        /// <remarks/>
        public void GetPriorGroupPurchaseInforAsync(int GroupID, object userState) {
            if ((this.GetPriorGroupPurchaseInforOperationCompleted == null)) {
                this.GetPriorGroupPurchaseInforOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPriorGroupPurchaseInforOperationCompleted);
            }
            this.InvokeAsync("GetPriorGroupPurchaseInfor", new object[] {
                        GroupID}, this.GetPriorGroupPurchaseInforOperationCompleted, userState);
        }
        
        private void OnGetPriorGroupPurchaseInforOperationCompleted(object arg) {
            if ((this.GetPriorGroupPurchaseInforCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPriorGroupPurchaseInforCompleted(this, new GetPriorGroupPurchaseInforCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCityList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCityList() {
            object[] results = this.Invoke("GetCityList", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCityListAsync() {
            this.GetCityListAsync(null);
        }
        
        /// <remarks/>
        public void GetCityListAsync(object userState) {
            if ((this.GetCityListOperationCompleted == null)) {
                this.GetCityListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityListOperationCompleted);
            }
            this.InvokeAsync("GetCityList", new object[0], this.GetCityListOperationCompleted, userState);
        }
        
        private void OnGetCityListOperationCompleted(object arg) {
            if ((this.GetCityListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityListCompleted(this, new GetCityListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCarSerialList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCarSerialList(int CityID) {
            object[] results = this.Invoke("GetCarSerialList", new object[] {
                        CityID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarSerialListAsync(int CityID) {
            this.GetCarSerialListAsync(CityID, null);
        }
        
        /// <remarks/>
        public void GetCarSerialListAsync(int CityID, object userState) {
            if ((this.GetCarSerialListOperationCompleted == null)) {
                this.GetCarSerialListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarSerialListOperationCompleted);
            }
            this.InvokeAsync("GetCarSerialList", new object[] {
                        CityID}, this.GetCarSerialListOperationCompleted, userState);
        }
        
        private void OnGetCarSerialListOperationCompleted(object arg) {
            if ((this.GetCarSerialListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarSerialListCompleted(this, new GetCarSerialListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCarSerialListTop", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCarSerialListTop(int CityID, int RowCount) {
            object[] results = this.Invoke("GetCarSerialListTop", new object[] {
                        CityID,
                        RowCount});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarSerialListTopAsync(int CityID, int RowCount) {
            this.GetCarSerialListTopAsync(CityID, RowCount, null);
        }
        
        /// <remarks/>
        public void GetCarSerialListTopAsync(int CityID, int RowCount, object userState) {
            if ((this.GetCarSerialListTopOperationCompleted == null)) {
                this.GetCarSerialListTopOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarSerialListTopOperationCompleted);
            }
            this.InvokeAsync("GetCarSerialListTop", new object[] {
                        CityID,
                        RowCount}, this.GetCarSerialListTopOperationCompleted, userState);
        }
        
        private void OnGetCarSerialListTopOperationCompleted(object arg) {
            if ((this.GetCarSerialListTopCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarSerialListTopCompleted(this, new GetCarSerialListTopCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddGoupSignUp", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AddGoupSignUp(GoupSignUpEntity entityGoupSignUp) {
            object[] results = this.Invoke("AddGoupSignUp", new object[] {
                        entityGoupSignUp});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AddGoupSignUpAsync(GoupSignUpEntity entityGoupSignUp) {
            this.AddGoupSignUpAsync(entityGoupSignUp, null);
        }
        
        /// <remarks/>
        public void AddGoupSignUpAsync(GoupSignUpEntity entityGoupSignUp, object userState) {
            if ((this.AddGoupSignUpOperationCompleted == null)) {
                this.AddGoupSignUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddGoupSignUpOperationCompleted);
            }
            this.InvokeAsync("AddGoupSignUp", new object[] {
                        entityGoupSignUp}, this.AddGoupSignUpOperationCompleted, userState);
        }
        
        private void OnAddGoupSignUpOperationCompleted(object arg) {
            if ((this.AddGoupSignUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddGoupSignUpCompleted(this, new AddGoupSignUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupCarsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetGroupCarsList(int GroupID) {
            object[] results = this.Invoke("GetGroupCarsList", new object[] {
                        GroupID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupCarsListAsync(int GroupID) {
            this.GetGroupCarsListAsync(GroupID, null);
        }
        
        /// <remarks/>
        public void GetGroupCarsListAsync(int GroupID, object userState) {
            if ((this.GetGroupCarsListOperationCompleted == null)) {
                this.GetGroupCarsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupCarsListOperationCompleted);
            }
            this.InvokeAsync("GetGroupCarsList", new object[] {
                        GroupID}, this.GetGroupCarsListOperationCompleted, userState);
        }
        
        private void OnGetGroupCarsListOperationCompleted(object arg) {
            if ((this.GetGroupCarsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupCarsListCompleted(this, new GetGroupCarsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastGroupCarsList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetLastGroupCarsList(int GroupID) {
            object[] results = this.Invoke("GetLastGroupCarsList", new object[] {
                        GroupID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastGroupCarsListAsync(int GroupID) {
            this.GetLastGroupCarsListAsync(GroupID, null);
        }
        
        /// <remarks/>
        public void GetLastGroupCarsListAsync(int GroupID, object userState) {
            if ((this.GetLastGroupCarsListOperationCompleted == null)) {
                this.GetLastGroupCarsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastGroupCarsListOperationCompleted);
            }
            this.InvokeAsync("GetLastGroupCarsList", new object[] {
                        GroupID}, this.GetLastGroupCarsListOperationCompleted, userState);
        }
        
        private void OnGetLastGroupCarsListOperationCompleted(object arg) {
            if ((this.GetLastGroupCarsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastGroupCarsListCompleted(this, new GetLastGroupCarsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCityNewGroupPurchaseList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCityNewGroupPurchaseList(int CityID) {
            object[] results = this.Invoke("GetCityNewGroupPurchaseList", new object[] {
                        CityID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCityNewGroupPurchaseListAsync(int CityID) {
            this.GetCityNewGroupPurchaseListAsync(CityID, null);
        }
        
        /// <remarks/>
        public void GetCityNewGroupPurchaseListAsync(int CityID, object userState) {
            if ((this.GetCityNewGroupPurchaseListOperationCompleted == null)) {
                this.GetCityNewGroupPurchaseListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityNewGroupPurchaseListOperationCompleted);
            }
            this.InvokeAsync("GetCityNewGroupPurchaseList", new object[] {
                        CityID}, this.GetCityNewGroupPurchaseListOperationCompleted, userState);
        }
        
        private void OnGetCityNewGroupPurchaseListOperationCompleted(object arg) {
            if ((this.GetCityNewGroupPurchaseListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityNewGroupPurchaseListCompleted(this, new GetCityNewGroupPurchaseListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCityListByCsID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCityListByCsID(int CsID) {
            object[] results = this.Invoke("GetCityListByCsID", new object[] {
                        CsID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCityListByCsIDAsync(int CsID) {
            this.GetCityListByCsIDAsync(CsID, null);
        }
        
        /// <remarks/>
        public void GetCityListByCsIDAsync(int CsID, object userState) {
            if ((this.GetCityListByCsIDOperationCompleted == null)) {
                this.GetCityListByCsIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCityListByCsIDOperationCompleted);
            }
            this.InvokeAsync("GetCityListByCsID", new object[] {
                        CsID}, this.GetCityListByCsIDOperationCompleted, userState);
        }
        
        private void OnGetCityListByCsIDOperationCompleted(object arg) {
            if ((this.GetCityListByCsIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCityListByCsIDCompleted(this, new GetCityListByCsIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCarListByCsID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCarListByCsID(int CsID) {
            object[] results = this.Invoke("GetCarListByCsID", new object[] {
                        CsID});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarListByCsIDAsync(int CsID) {
            this.GetCarListByCsIDAsync(CsID, null);
        }
        
        /// <remarks/>
        public void GetCarListByCsIDAsync(int CsID, object userState) {
            if ((this.GetCarListByCsIDOperationCompleted == null)) {
                this.GetCarListByCsIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarListByCsIDOperationCompleted);
            }
            this.InvokeAsync("GetCarListByCsID", new object[] {
                        CsID}, this.GetCarListByCsIDOperationCompleted, userState);
        }
        
        private void OnGetCarListByCsIDOperationCompleted(object arg) {
            if ((this.GetCarListByCsIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarListByCsIDCompleted(this, new GetCarListByCsIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupPurchaseSearchCondition", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetGroupPurchaseSearchCondition(int CityID, int MasterBrandID, int PriceID, string CarLevel) {
            object[] results = this.Invoke("GetGroupPurchaseSearchCondition", new object[] {
                        CityID,
                        MasterBrandID,
                        PriceID,
                        CarLevel});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupPurchaseSearchConditionAsync(int CityID, int MasterBrandID, int PriceID, string CarLevel) {
            this.GetGroupPurchaseSearchConditionAsync(CityID, MasterBrandID, PriceID, CarLevel, null);
        }
        
        /// <remarks/>
        public void GetGroupPurchaseSearchConditionAsync(int CityID, int MasterBrandID, int PriceID, string CarLevel, object userState) {
            if ((this.GetGroupPurchaseSearchConditionOperationCompleted == null)) {
                this.GetGroupPurchaseSearchConditionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupPurchaseSearchConditionOperationCompleted);
            }
            this.InvokeAsync("GetGroupPurchaseSearchCondition", new object[] {
                        CityID,
                        MasterBrandID,
                        PriceID,
                        CarLevel}, this.GetGroupPurchaseSearchConditionOperationCompleted, userState);
        }
        
        private void OnGetGroupPurchaseSearchConditionOperationCompleted(object arg) {
            if ((this.GetGroupPurchaseSearchConditionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupPurchaseSearchConditionCompleted(this, new GetGroupPurchaseSearchConditionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGroupPurchaseSearchContent", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetGroupPurchaseSearchContent(int CityID, int MasterBrandID, int PriceID, string CarLevel) {
            object[] results = this.Invoke("GetGroupPurchaseSearchContent", new object[] {
                        CityID,
                        MasterBrandID,
                        PriceID,
                        CarLevel});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetGroupPurchaseSearchContentAsync(int CityID, int MasterBrandID, int PriceID, string CarLevel) {
            this.GetGroupPurchaseSearchContentAsync(CityID, MasterBrandID, PriceID, CarLevel, null);
        }
        
        /// <remarks/>
        public void GetGroupPurchaseSearchContentAsync(int CityID, int MasterBrandID, int PriceID, string CarLevel, object userState) {
            if ((this.GetGroupPurchaseSearchContentOperationCompleted == null)) {
                this.GetGroupPurchaseSearchContentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGroupPurchaseSearchContentOperationCompleted);
            }
            this.InvokeAsync("GetGroupPurchaseSearchContent", new object[] {
                        CityID,
                        MasterBrandID,
                        PriceID,
                        CarLevel}, this.GetGroupPurchaseSearchContentOperationCompleted, userState);
        }
        
        private void OnGetGroupPurchaseSearchContentOperationCompleted(object arg) {
            if ((this.GetGroupPurchaseSearchContentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGroupPurchaseSearchContentCompleted(this, new GetGroupPurchaseSearchContentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetActiveGroupPurchaseTopList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetActiveGroupPurchaseTopList(int CityID, int RowCount, int OrderType) {
            object[] results = this.Invoke("GetActiveGroupPurchaseTopList", new object[] {
                        CityID,
                        RowCount,
                        OrderType});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchaseTopListAsync(int CityID, int RowCount, int OrderType) {
            this.GetActiveGroupPurchaseTopListAsync(CityID, RowCount, OrderType, null);
        }
        
        /// <remarks/>
        public void GetActiveGroupPurchaseTopListAsync(int CityID, int RowCount, int OrderType, object userState) {
            if ((this.GetActiveGroupPurchaseTopListOperationCompleted == null)) {
                this.GetActiveGroupPurchaseTopListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetActiveGroupPurchaseTopListOperationCompleted);
            }
            this.InvokeAsync("GetActiveGroupPurchaseTopList", new object[] {
                        CityID,
                        RowCount,
                        OrderType}, this.GetActiveGroupPurchaseTopListOperationCompleted, userState);
        }
        
        private void OnGetActiveGroupPurchaseTopListOperationCompleted(object arg) {
            if ((this.GetActiveGroupPurchaseTopListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetActiveGroupPurchaseTopListCompleted(this, new GetActiveGroupPurchaseTopListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class DasSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private System.Guid tokenKeyField;
        
        private string authorizeCodeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public System.Guid TokenKey {
            get {
                return this.tokenKeyField;
            }
            set {
                this.tokenKeyField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorizeCode {
            get {
                return this.authorizeCodeField;
            }
            set {
                this.authorizeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GoupSignUpEntity {
        
        private int signUpIDField;
        
        private int groupIDField;
        
        private int carIDField;
        
        private int userIDField;
        
        private string userNameField;
        
        private string trueNameField;
        
        private short sexField;
        
        private string telphoneField;
        
        private string mailField;
        
        private string summaryField;
        
        private System.DateTime createTimeField;
        
        private System.DateTime updateTimeField;
        
        private string colorField;
        
        private int cityIDField;
        
        private short isActiveField;
        
        /// <remarks/>
        public int SignUpID {
            get {
                return this.signUpIDField;
            }
            set {
                this.signUpIDField = value;
            }
        }
        
        /// <remarks/>
        public int GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public int CarID {
            get {
                return this.carIDField;
            }
            set {
                this.carIDField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string TrueName {
            get {
                return this.trueNameField;
            }
            set {
                this.trueNameField = value;
            }
        }
        
        /// <remarks/>
        public short Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Telphone {
            get {
                return this.telphoneField;
            }
            set {
                this.telphoneField = value;
            }
        }
        
        /// <remarks/>
        public string Mail {
            get {
                return this.mailField;
            }
            set {
                this.mailField = value;
            }
        }
        
        /// <remarks/>
        public string Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
            }
        }
        
        /// <remarks/>
        public int CityID {
            get {
                return this.cityIDField;
            }
            set {
                this.cityIDField = value;
            }
        }
        
        /// <remarks/>
        public short IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GroupPurchaseEntity {
        
        private int groupIDField;
        
        private string groupNameField;
        
        private int cityIDField;
        
        private int serialIDField;
        
        private int dealerIDField;
        
        private int signUpCountField;
        
        private string carPicField;
        
        private System.DateTime startTimeField;
        
        private System.DateTime stopTimeField;
        
        private decimal minPriceField;
        
        private decimal maxPriceField;
        
        private decimal avgDiscountField;
        
        private decimal costSavingField;
        
        private short periodsField;
        
        private System.DateTime createTimeField;
        
        private System.DateTime updateTimeField;
        
        private short isActiveField;
        
        private short isLockField;
        
        /// <remarks/>
        public int GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string GroupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        public int CityID {
            get {
                return this.cityIDField;
            }
            set {
                this.cityIDField = value;
            }
        }
        
        /// <remarks/>
        public int SerialID {
            get {
                return this.serialIDField;
            }
            set {
                this.serialIDField = value;
            }
        }
        
        /// <remarks/>
        public int DealerID {
            get {
                return this.dealerIDField;
            }
            set {
                this.dealerIDField = value;
            }
        }
        
        /// <remarks/>
        public int SignUpCount {
            get {
                return this.signUpCountField;
            }
            set {
                this.signUpCountField = value;
            }
        }
        
        /// <remarks/>
        public string CarPic {
            get {
                return this.carPicField;
            }
            set {
                this.carPicField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StopTime {
            get {
                return this.stopTimeField;
            }
            set {
                this.stopTimeField = value;
            }
        }
        
        /// <remarks/>
        public decimal MinPrice {
            get {
                return this.minPriceField;
            }
            set {
                this.minPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal MaxPrice {
            get {
                return this.maxPriceField;
            }
            set {
                this.maxPriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal AvgDiscount {
            get {
                return this.avgDiscountField;
            }
            set {
                this.avgDiscountField = value;
            }
        }
        
        /// <remarks/>
        public decimal CostSaving {
            get {
                return this.costSavingField;
            }
            set {
                this.costSavingField = value;
            }
        }
        
        /// <remarks/>
        public short Periods {
            get {
                return this.periodsField;
            }
            set {
                this.periodsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime UpdateTime {
            get {
                return this.updateTimeField;
            }
            set {
                this.updateTimeField = value;
            }
        }
        
        /// <remarks/>
        public short IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public short IsLock {
            get {
                return this.isLockField;
            }
            set {
                this.isLockField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetLatestOrderUserCompletedEventHandler(object sender, GetLatestOrderUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLatestOrderUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLatestOrderUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetActiveGroupPurchaseListCompletedEventHandler(object sender, GetActiveGroupPurchaseListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveGroupPurchaseListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveGroupPurchaseListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetActiveGroupPurchasePageListCompletedEventHandler(object sender, GetActiveGroupPurchasePageListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveGroupPurchasePageListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveGroupPurchasePageListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetActiveGroupPurchaseByCityAndSerialCompletedEventHandler(object sender, GetActiveGroupPurchaseByCityAndSerialCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveGroupPurchaseByCityAndSerialCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveGroupPurchaseByCityAndSerialCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupPurchaseEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupPurchaseEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetActiveGroupPurchaseTopListByCityCompletedEventHandler(object sender, GetActiveGroupPurchaseTopListByCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveGroupPurchaseTopListByCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveGroupPurchaseTopListByCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetHistoryGroupPurchaseListCompletedEventHandler(object sender, GetHistoryGroupPurchaseListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHistoryGroupPurchaseListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHistoryGroupPurchaseListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGroupPurchaseInforCompletedEventHandler(object sender, GetGroupPurchaseInforCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupPurchaseInforCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupPurchaseInforCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupPurchaseEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupPurchaseEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPriorGroupPurchaseInforCompletedEventHandler(object sender, GetPriorGroupPurchaseInforCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPriorGroupPurchaseInforCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPriorGroupPurchaseInforCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupPurchaseEntity Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupPurchaseEntity)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCityListCompletedEventHandler(object sender, GetCityListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCityListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCarSerialListCompletedEventHandler(object sender, GetCarSerialListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarSerialListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarSerialListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCarSerialListTopCompletedEventHandler(object sender, GetCarSerialListTopCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarSerialListTopCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarSerialListTopCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddGoupSignUpCompletedEventHandler(object sender, AddGoupSignUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddGoupSignUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddGoupSignUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGroupCarsListCompletedEventHandler(object sender, GetGroupCarsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupCarsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupCarsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetLastGroupCarsListCompletedEventHandler(object sender, GetLastGroupCarsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastGroupCarsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastGroupCarsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCityNewGroupPurchaseListCompletedEventHandler(object sender, GetCityNewGroupPurchaseListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityNewGroupPurchaseListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCityNewGroupPurchaseListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCityListByCsIDCompletedEventHandler(object sender, GetCityListByCsIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCityListByCsIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCityListByCsIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCarListByCsIDCompletedEventHandler(object sender, GetCarListByCsIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarListByCsIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarListByCsIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGroupPurchaseSearchConditionCompletedEventHandler(object sender, GetGroupPurchaseSearchConditionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupPurchaseSearchConditionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupPurchaseSearchConditionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetGroupPurchaseSearchContentCompletedEventHandler(object sender, GetGroupPurchaseSearchContentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGroupPurchaseSearchContentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGroupPurchaseSearchContentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetActiveGroupPurchaseTopListCompletedEventHandler(object sender, GetActiveGroupPurchaseTopListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetActiveGroupPurchaseTopListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetActiveGroupPurchaseTopListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591