//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.269 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.CarChannel.Common.com.bitauto.index {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IndexDataSoap", Namespace="http://index.bitauto.com/")]
    public partial class IndexData : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetLastDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFirstDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShangPaiLastDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexTopListByLastDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexTopListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexTopListProOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompareNear30DayTopListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexGrowthTopListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexDataListByLastDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexDataListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegionalIndexDataListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompareNear30DaysIndexDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompareIndexDataByLastDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompareIndexDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIndexTrendDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegionalIndexTrendDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCitySortListByLastDateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCitySortListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRegionSortListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IndexData() {
            this.Url = global::BitAuto.CarChannel.Common.Properties.Settings.Default.Common_com_bitauto_index_IndexData;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLastDateCompletedEventHandler GetLastDateCompleted;
        
        /// <remarks/>
        public event GetFirstDateCompletedEventHandler GetFirstDateCompleted;
        
        /// <remarks/>
        public event GetShangPaiLastDateCompletedEventHandler GetShangPaiLastDateCompleted;
        
        /// <remarks/>
        public event GetIndexTopListByLastDateCompletedEventHandler GetIndexTopListByLastDateCompleted;
        
        /// <remarks/>
        public event GetIndexTopListCompletedEventHandler GetIndexTopListCompleted;
        
        /// <remarks/>
        public event GetIndexTopListProCompletedEventHandler GetIndexTopListProCompleted;
        
        /// <remarks/>
        public event GetCompareNear30DayTopListCompletedEventHandler GetCompareNear30DayTopListCompleted;
        
        /// <remarks/>
        public event GetIndexGrowthTopListCompletedEventHandler GetIndexGrowthTopListCompleted;
        
        /// <remarks/>
        public event GetIndexDataListByLastDateCompletedEventHandler GetIndexDataListByLastDateCompleted;
        
        /// <remarks/>
        public event GetIndexDataListCompletedEventHandler GetIndexDataListCompleted;
        
        /// <remarks/>
        public event GetRegionalIndexDataListCompletedEventHandler GetRegionalIndexDataListCompleted;
        
        /// <remarks/>
        public event GetCompareNear30DaysIndexDataCompletedEventHandler GetCompareNear30DaysIndexDataCompleted;
        
        /// <remarks/>
        public event GetCompareIndexDataByLastDateCompletedEventHandler GetCompareIndexDataByLastDateCompleted;
        
        /// <remarks/>
        public event GetCompareIndexDataCompletedEventHandler GetCompareIndexDataCompleted;
        
        /// <remarks/>
        public event GetIndexTrendDataCompletedEventHandler GetIndexTrendDataCompleted;
        
        /// <remarks/>
        public event GetRegionalIndexTrendDataCompletedEventHandler GetRegionalIndexTrendDataCompleted;
        
        /// <remarks/>
        public event GetCitySortListByLastDateCompletedEventHandler GetCitySortListByLastDateCompleted;
        
        /// <remarks/>
        public event GetCitySortListCompletedEventHandler GetCitySortListCompleted;
        
        /// <remarks/>
        public event GetRegionSortListCompletedEventHandler GetRegionSortListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetLastDate", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DateObj GetLastDate(IndexType indexType, DateType dateType) {
            object[] results = this.Invoke("GetLastDate", new object[] {
                        indexType,
                        dateType});
            return ((DateObj)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastDateAsync(IndexType indexType, DateType dateType) {
            this.GetLastDateAsync(indexType, dateType, null);
        }
        
        /// <remarks/>
        public void GetLastDateAsync(IndexType indexType, DateType dateType, object userState) {
            if ((this.GetLastDateOperationCompleted == null)) {
                this.GetLastDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastDateOperationCompleted);
            }
            this.InvokeAsync("GetLastDate", new object[] {
                        indexType,
                        dateType}, this.GetLastDateOperationCompleted, userState);
        }
        
        private void OnGetLastDateOperationCompleted(object arg) {
            if ((this.GetLastDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastDateCompleted(this, new GetLastDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetFirstDate", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DateObj GetFirstDate(IndexType indexType, DateType dateType) {
            object[] results = this.Invoke("GetFirstDate", new object[] {
                        indexType,
                        dateType});
            return ((DateObj)(results[0]));
        }
        
        /// <remarks/>
        public void GetFirstDateAsync(IndexType indexType, DateType dateType) {
            this.GetFirstDateAsync(indexType, dateType, null);
        }
        
        /// <remarks/>
        public void GetFirstDateAsync(IndexType indexType, DateType dateType, object userState) {
            if ((this.GetFirstDateOperationCompleted == null)) {
                this.GetFirstDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFirstDateOperationCompleted);
            }
            this.InvokeAsync("GetFirstDate", new object[] {
                        indexType,
                        dateType}, this.GetFirstDateOperationCompleted, userState);
        }
        
        private void OnGetFirstDateOperationCompleted(object arg) {
            if ((this.GetFirstDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFirstDateCompleted(this, new GetFirstDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetShangPaiLastDate", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DateObj GetShangPaiLastDate(DateType dateType) {
            object[] results = this.Invoke("GetShangPaiLastDate", new object[] {
                        dateType});
            return ((DateObj)(results[0]));
        }
        
        /// <remarks/>
        public void GetShangPaiLastDateAsync(DateType dateType) {
            this.GetShangPaiLastDateAsync(dateType, null);
        }
        
        /// <remarks/>
        public void GetShangPaiLastDateAsync(DateType dateType, object userState) {
            if ((this.GetShangPaiLastDateOperationCompleted == null)) {
                this.GetShangPaiLastDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShangPaiLastDateOperationCompleted);
            }
            this.InvokeAsync("GetShangPaiLastDate", new object[] {
                        dateType}, this.GetShangPaiLastDateOperationCompleted, userState);
        }
        
        private void OnGetShangPaiLastDateOperationCompleted(object arg) {
            if ((this.GetShangPaiLastDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShangPaiLastDateCompleted(this, new GetShangPaiLastDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetIndexTopListByLastDate", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetIndexTopListByLastDate(IndexType indexType, int cityId) {
            object[] results = this.Invoke("GetIndexTopListByLastDate", new object[] {
                        indexType,
                        cityId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexTopListByLastDateAsync(IndexType indexType, int cityId) {
            this.GetIndexTopListByLastDateAsync(indexType, cityId, null);
        }
        
        /// <remarks/>
        public void GetIndexTopListByLastDateAsync(IndexType indexType, int cityId, object userState) {
            if ((this.GetIndexTopListByLastDateOperationCompleted == null)) {
                this.GetIndexTopListByLastDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexTopListByLastDateOperationCompleted);
            }
            this.InvokeAsync("GetIndexTopListByLastDate", new object[] {
                        indexType,
                        cityId}, this.GetIndexTopListByLastDateOperationCompleted, userState);
        }
        
        private void OnGetIndexTopListByLastDateOperationCompleted(object arg) {
            if ((this.GetIndexTopListByLastDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexTopListByLastDateCompleted(this, new GetIndexTopListByLastDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetIndexTopList", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetIndexTopList(IndexType indexType, int cityId, DateObj date) {
            object[] results = this.Invoke("GetIndexTopList", new object[] {
                        indexType,
                        cityId,
                        date});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexTopListAsync(IndexType indexType, int cityId, DateObj date) {
            this.GetIndexTopListAsync(indexType, cityId, date, null);
        }
        
        /// <remarks/>
        public void GetIndexTopListAsync(IndexType indexType, int cityId, DateObj date, object userState) {
            if ((this.GetIndexTopListOperationCompleted == null)) {
                this.GetIndexTopListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexTopListOperationCompleted);
            }
            this.InvokeAsync("GetIndexTopList", new object[] {
                        indexType,
                        cityId,
                        date}, this.GetIndexTopListOperationCompleted, userState);
        }
        
        private void OnGetIndexTopListOperationCompleted(object arg) {
            if ((this.GetIndexTopListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexTopListCompleted(this, new GetIndexTopListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetIndexTopListPro", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetIndexTopListPro(IndexType indexType, RegionType regionType, int regionId, DateObj date) {
            object[] results = this.Invoke("GetIndexTopListPro", new object[] {
                        indexType,
                        regionType,
                        regionId,
                        date});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexTopListProAsync(IndexType indexType, RegionType regionType, int regionId, DateObj date) {
            this.GetIndexTopListProAsync(indexType, regionType, regionId, date, null);
        }
        
        /// <remarks/>
        public void GetIndexTopListProAsync(IndexType indexType, RegionType regionType, int regionId, DateObj date, object userState) {
            if ((this.GetIndexTopListProOperationCompleted == null)) {
                this.GetIndexTopListProOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexTopListProOperationCompleted);
            }
            this.InvokeAsync("GetIndexTopListPro", new object[] {
                        indexType,
                        regionType,
                        regionId,
                        date}, this.GetIndexTopListProOperationCompleted, userState);
        }
        
        private void OnGetIndexTopListProOperationCompleted(object arg) {
            if ((this.GetIndexTopListProCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexTopListProCompleted(this, new GetIndexTopListProCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetCompareNear30DayTopList", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetCompareNear30DayTopList() {
            object[] results = this.Invoke("GetCompareNear30DayTopList", new object[0]);
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetCompareNear30DayTopListAsync() {
            this.GetCompareNear30DayTopListAsync(null);
        }
        
        /// <remarks/>
        public void GetCompareNear30DayTopListAsync(object userState) {
            if ((this.GetCompareNear30DayTopListOperationCompleted == null)) {
                this.GetCompareNear30DayTopListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompareNear30DayTopListOperationCompleted);
            }
            this.InvokeAsync("GetCompareNear30DayTopList", new object[0], this.GetCompareNear30DayTopListOperationCompleted, userState);
        }
        
        private void OnGetCompareNear30DayTopListOperationCompleted(object arg) {
            if ((this.GetCompareNear30DayTopListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompareNear30DayTopListCompleted(this, new GetCompareNear30DayTopListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetIndexGrowthTopList", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetIndexGrowthTopList(IndexType indexType, RegionType regionType, int regionId, BrandType brandType, string levelSpell, DateObj date) {
            object[] results = this.Invoke("GetIndexGrowthTopList", new object[] {
                        indexType,
                        regionType,
                        regionId,
                        brandType,
                        levelSpell,
                        date});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexGrowthTopListAsync(IndexType indexType, RegionType regionType, int regionId, BrandType brandType, string levelSpell, DateObj date) {
            this.GetIndexGrowthTopListAsync(indexType, regionType, regionId, brandType, levelSpell, date, null);
        }
        
        /// <remarks/>
        public void GetIndexGrowthTopListAsync(IndexType indexType, RegionType regionType, int regionId, BrandType brandType, string levelSpell, DateObj date, object userState) {
            if ((this.GetIndexGrowthTopListOperationCompleted == null)) {
                this.GetIndexGrowthTopListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexGrowthTopListOperationCompleted);
            }
            this.InvokeAsync("GetIndexGrowthTopList", new object[] {
                        indexType,
                        regionType,
                        regionId,
                        brandType,
                        levelSpell,
                        date}, this.GetIndexGrowthTopListOperationCompleted, userState);
        }
        
        private void OnGetIndexGrowthTopListOperationCompleted(object arg) {
            if ((this.GetIndexGrowthTopListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexGrowthTopListCompleted(this, new GetIndexGrowthTopListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetIndexDataListByLastDate", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IndexItem[] GetIndexDataListByLastDate(IndexType indexType, BrandType brandType, string levelSpell, int cityId) {
            object[] results = this.Invoke("GetIndexDataListByLastDate", new object[] {
                        indexType,
                        brandType,
                        levelSpell,
                        cityId});
            return ((IndexItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexDataListByLastDateAsync(IndexType indexType, BrandType brandType, string levelSpell, int cityId) {
            this.GetIndexDataListByLastDateAsync(indexType, brandType, levelSpell, cityId, null);
        }
        
        /// <remarks/>
        public void GetIndexDataListByLastDateAsync(IndexType indexType, BrandType brandType, string levelSpell, int cityId, object userState) {
            if ((this.GetIndexDataListByLastDateOperationCompleted == null)) {
                this.GetIndexDataListByLastDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexDataListByLastDateOperationCompleted);
            }
            this.InvokeAsync("GetIndexDataListByLastDate", new object[] {
                        indexType,
                        brandType,
                        levelSpell,
                        cityId}, this.GetIndexDataListByLastDateOperationCompleted, userState);
        }
        
        private void OnGetIndexDataListByLastDateOperationCompleted(object arg) {
            if ((this.GetIndexDataListByLastDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexDataListByLastDateCompleted(this, new GetIndexDataListByLastDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetIndexDataList", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IndexItem[] GetIndexDataList(IndexType indexType, BrandType brandType, string levelSpell, int cityId, DateObj date) {
            object[] results = this.Invoke("GetIndexDataList", new object[] {
                        indexType,
                        brandType,
                        levelSpell,
                        cityId,
                        date});
            return ((IndexItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexDataListAsync(IndexType indexType, BrandType brandType, string levelSpell, int cityId, DateObj date) {
            this.GetIndexDataListAsync(indexType, brandType, levelSpell, cityId, date, null);
        }
        
        /// <remarks/>
        public void GetIndexDataListAsync(IndexType indexType, BrandType brandType, string levelSpell, int cityId, DateObj date, object userState) {
            if ((this.GetIndexDataListOperationCompleted == null)) {
                this.GetIndexDataListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexDataListOperationCompleted);
            }
            this.InvokeAsync("GetIndexDataList", new object[] {
                        indexType,
                        brandType,
                        levelSpell,
                        cityId,
                        date}, this.GetIndexDataListOperationCompleted, userState);
        }
        
        private void OnGetIndexDataListOperationCompleted(object arg) {
            if ((this.GetIndexDataListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexDataListCompleted(this, new GetIndexDataListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetRegionalIndexDataList", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IndexItem[] GetRegionalIndexDataList(IndexType indexType, BrandType brandType, string levelSpell, RegionType regionType, int regionId, DateObj date) {
            object[] results = this.Invoke("GetRegionalIndexDataList", new object[] {
                        indexType,
                        brandType,
                        levelSpell,
                        regionType,
                        regionId,
                        date});
            return ((IndexItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegionalIndexDataListAsync(IndexType indexType, BrandType brandType, string levelSpell, RegionType regionType, int regionId, DateObj date) {
            this.GetRegionalIndexDataListAsync(indexType, brandType, levelSpell, regionType, regionId, date, null);
        }
        
        /// <remarks/>
        public void GetRegionalIndexDataListAsync(IndexType indexType, BrandType brandType, string levelSpell, RegionType regionType, int regionId, DateObj date, object userState) {
            if ((this.GetRegionalIndexDataListOperationCompleted == null)) {
                this.GetRegionalIndexDataListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegionalIndexDataListOperationCompleted);
            }
            this.InvokeAsync("GetRegionalIndexDataList", new object[] {
                        indexType,
                        brandType,
                        levelSpell,
                        regionType,
                        regionId,
                        date}, this.GetRegionalIndexDataListOperationCompleted, userState);
        }
        
        private void OnGetRegionalIndexDataListOperationCompleted(object arg) {
            if ((this.GetRegionalIndexDataListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegionalIndexDataListCompleted(this, new GetRegionalIndexDataListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetCompareNear30DaysIndexData", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IndexItem[] GetCompareNear30DaysIndexData(int serialId, int cityId) {
            object[] results = this.Invoke("GetCompareNear30DaysIndexData", new object[] {
                        serialId,
                        cityId});
            return ((IndexItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompareNear30DaysIndexDataAsync(int serialId, int cityId) {
            this.GetCompareNear30DaysIndexDataAsync(serialId, cityId, null);
        }
        
        /// <remarks/>
        public void GetCompareNear30DaysIndexDataAsync(int serialId, int cityId, object userState) {
            if ((this.GetCompareNear30DaysIndexDataOperationCompleted == null)) {
                this.GetCompareNear30DaysIndexDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompareNear30DaysIndexDataOperationCompleted);
            }
            this.InvokeAsync("GetCompareNear30DaysIndexData", new object[] {
                        serialId,
                        cityId}, this.GetCompareNear30DaysIndexDataOperationCompleted, userState);
        }
        
        private void OnGetCompareNear30DaysIndexDataOperationCompleted(object arg) {
            if ((this.GetCompareNear30DaysIndexDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompareNear30DaysIndexDataCompleted(this, new GetCompareNear30DaysIndexDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetCompareIndexDataByLastDate", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IndexItem[] GetCompareIndexDataByLastDate(int serialId, int cityId) {
            object[] results = this.Invoke("GetCompareIndexDataByLastDate", new object[] {
                        serialId,
                        cityId});
            return ((IndexItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompareIndexDataByLastDateAsync(int serialId, int cityId) {
            this.GetCompareIndexDataByLastDateAsync(serialId, cityId, null);
        }
        
        /// <remarks/>
        public void GetCompareIndexDataByLastDateAsync(int serialId, int cityId, object userState) {
            if ((this.GetCompareIndexDataByLastDateOperationCompleted == null)) {
                this.GetCompareIndexDataByLastDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompareIndexDataByLastDateOperationCompleted);
            }
            this.InvokeAsync("GetCompareIndexDataByLastDate", new object[] {
                        serialId,
                        cityId}, this.GetCompareIndexDataByLastDateOperationCompleted, userState);
        }
        
        private void OnGetCompareIndexDataByLastDateOperationCompleted(object arg) {
            if ((this.GetCompareIndexDataByLastDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompareIndexDataByLastDateCompleted(this, new GetCompareIndexDataByLastDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetCompareIndexData", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IndexItem[] GetCompareIndexData(int serialId, int cityId, DateObj date) {
            object[] results = this.Invoke("GetCompareIndexData", new object[] {
                        serialId,
                        cityId,
                        date});
            return ((IndexItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompareIndexDataAsync(int serialId, int cityId, DateObj date) {
            this.GetCompareIndexDataAsync(serialId, cityId, date, null);
        }
        
        /// <remarks/>
        public void GetCompareIndexDataAsync(int serialId, int cityId, DateObj date, object userState) {
            if ((this.GetCompareIndexDataOperationCompleted == null)) {
                this.GetCompareIndexDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompareIndexDataOperationCompleted);
            }
            this.InvokeAsync("GetCompareIndexData", new object[] {
                        serialId,
                        cityId,
                        date}, this.GetCompareIndexDataOperationCompleted, userState);
        }
        
        private void OnGetCompareIndexDataOperationCompleted(object arg) {
            if ((this.GetCompareIndexDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompareIndexDataCompleted(this, new GetCompareIndexDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetIndexTrendData", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode GetIndexTrendData(IndexType indexType, BrandType brandType, int cityId, int itemId) {
            object[] results = this.Invoke("GetIndexTrendData", new object[] {
                        indexType,
                        brandType,
                        cityId,
                        itemId});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetIndexTrendDataAsync(IndexType indexType, BrandType brandType, int cityId, int itemId) {
            this.GetIndexTrendDataAsync(indexType, brandType, cityId, itemId, null);
        }
        
        /// <remarks/>
        public void GetIndexTrendDataAsync(IndexType indexType, BrandType brandType, int cityId, int itemId, object userState) {
            if ((this.GetIndexTrendDataOperationCompleted == null)) {
                this.GetIndexTrendDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIndexTrendDataOperationCompleted);
            }
            this.InvokeAsync("GetIndexTrendData", new object[] {
                        indexType,
                        brandType,
                        cityId,
                        itemId}, this.GetIndexTrendDataOperationCompleted, userState);
        }
        
        private void OnGetIndexTrendDataOperationCompleted(object arg) {
            if ((this.GetIndexTrendDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIndexTrendDataCompleted(this, new GetIndexTrendDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetRegionalIndexTrendData", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IndexTrendItem[] GetRegionalIndexTrendData(IndexType indexType, BrandType brandType, RegionType regionType, int regionId, int itemId, DateType dateType) {
            object[] results = this.Invoke("GetRegionalIndexTrendData", new object[] {
                        indexType,
                        brandType,
                        regionType,
                        regionId,
                        itemId,
                        dateType});
            return ((IndexTrendItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegionalIndexTrendDataAsync(IndexType indexType, BrandType brandType, RegionType regionType, int regionId, int itemId, DateType dateType) {
            this.GetRegionalIndexTrendDataAsync(indexType, brandType, regionType, regionId, itemId, dateType, null);
        }
        
        /// <remarks/>
        public void GetRegionalIndexTrendDataAsync(IndexType indexType, BrandType brandType, RegionType regionType, int regionId, int itemId, DateType dateType, object userState) {
            if ((this.GetRegionalIndexTrendDataOperationCompleted == null)) {
                this.GetRegionalIndexTrendDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegionalIndexTrendDataOperationCompleted);
            }
            this.InvokeAsync("GetRegionalIndexTrendData", new object[] {
                        indexType,
                        brandType,
                        regionType,
                        regionId,
                        itemId,
                        dateType}, this.GetRegionalIndexTrendDataOperationCompleted, userState);
        }
        
        private void OnGetRegionalIndexTrendDataOperationCompleted(object arg) {
            if ((this.GetRegionalIndexTrendDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegionalIndexTrendDataCompleted(this, new GetRegionalIndexTrendDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetCitySortListByLastDate", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CitySortItem[] GetCitySortListByLastDate(IndexType indexType, BrandType brandType, int itemId) {
            object[] results = this.Invoke("GetCitySortListByLastDate", new object[] {
                        indexType,
                        brandType,
                        itemId});
            return ((CitySortItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCitySortListByLastDateAsync(IndexType indexType, BrandType brandType, int itemId) {
            this.GetCitySortListByLastDateAsync(indexType, brandType, itemId, null);
        }
        
        /// <remarks/>
        public void GetCitySortListByLastDateAsync(IndexType indexType, BrandType brandType, int itemId, object userState) {
            if ((this.GetCitySortListByLastDateOperationCompleted == null)) {
                this.GetCitySortListByLastDateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCitySortListByLastDateOperationCompleted);
            }
            this.InvokeAsync("GetCitySortListByLastDate", new object[] {
                        indexType,
                        brandType,
                        itemId}, this.GetCitySortListByLastDateOperationCompleted, userState);
        }
        
        private void OnGetCitySortListByLastDateOperationCompleted(object arg) {
            if ((this.GetCitySortListByLastDateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCitySortListByLastDateCompleted(this, new GetCitySortListByLastDateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetCitySortList", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CitySortItem[] GetCitySortList(IndexType indexType, BrandType brandType, int itemId, DateObj date) {
            object[] results = this.Invoke("GetCitySortList", new object[] {
                        indexType,
                        brandType,
                        itemId,
                        date});
            return ((CitySortItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCitySortListAsync(IndexType indexType, BrandType brandType, int itemId, DateObj date) {
            this.GetCitySortListAsync(indexType, brandType, itemId, date, null);
        }
        
        /// <remarks/>
        public void GetCitySortListAsync(IndexType indexType, BrandType brandType, int itemId, DateObj date, object userState) {
            if ((this.GetCitySortListOperationCompleted == null)) {
                this.GetCitySortListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCitySortListOperationCompleted);
            }
            this.InvokeAsync("GetCitySortList", new object[] {
                        indexType,
                        brandType,
                        itemId,
                        date}, this.GetCitySortListOperationCompleted, userState);
        }
        
        private void OnGetCitySortListOperationCompleted(object arg) {
            if ((this.GetCitySortListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCitySortListCompleted(this, new GetCitySortListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://index.bitauto.com/GetRegionSortList", RequestNamespace="http://index.bitauto.com/", ResponseNamespace="http://index.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IndexRegionSortItem[] GetRegionSortList(RegionType regionType, IndexType indexType, BrandType brandType, int itemId, DateObj date) {
            object[] results = this.Invoke("GetRegionSortList", new object[] {
                        regionType,
                        indexType,
                        brandType,
                        itemId,
                        date});
            return ((IndexRegionSortItem[])(results[0]));
        }
        
        /// <remarks/>
        public void GetRegionSortListAsync(RegionType regionType, IndexType indexType, BrandType brandType, int itemId, DateObj date) {
            this.GetRegionSortListAsync(regionType, indexType, brandType, itemId, date, null);
        }
        
        /// <remarks/>
        public void GetRegionSortListAsync(RegionType regionType, IndexType indexType, BrandType brandType, int itemId, DateObj date, object userState) {
            if ((this.GetRegionSortListOperationCompleted == null)) {
                this.GetRegionSortListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRegionSortListOperationCompleted);
            }
            this.InvokeAsync("GetRegionSortList", new object[] {
                        regionType,
                        indexType,
                        brandType,
                        itemId,
                        date}, this.GetRegionSortListOperationCompleted, userState);
        }
        
        private void OnGetRegionSortListOperationCompleted(object arg) {
            if ((this.GetRegionSortListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRegionSortListCompleted(this, new GetRegionSortListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://index.bitauto.com/")]
    public enum IndexType {
        
        /// <remarks/>
        UV,
        
        /// <remarks/>
        Dealer,
        
        /// <remarks/>
        Sale,
        
        /// <remarks/>
        Media,
        
        /// <remarks/>
        Compare,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://index.bitauto.com/")]
    public enum DateType {
        
        /// <remarks/>
        Season,
        
        /// <remarks/>
        Month,
        
        /// <remarks/>
        Week,
        
        /// <remarks/>
        Near30day,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://index.bitauto.com/")]
    public partial class DateObj {
        
        private int yearField;
        
        private int dateNumField;
        
        private DateType dateTypeField;
        
        /// <remarks/>
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public int DateNum {
            get {
                return this.dateNumField;
            }
            set {
                this.dateNumField = value;
            }
        }
        
        /// <remarks/>
        public DateType DateType {
            get {
                return this.dateTypeField;
            }
            set {
                this.dateTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CitySortItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://index.bitauto.com/")]
    public partial class IndexRegionSortItem {
        
        private int regionIdField;
        
        private string regionNameField;
        
        private int sortField;
        
        private int indexNumField;
        
        /// <remarks/>
        public int RegionId {
            get {
                return this.regionIdField;
            }
            set {
                this.regionIdField = value;
            }
        }
        
        /// <remarks/>
        public string RegionName {
            get {
                return this.regionNameField;
            }
            set {
                this.regionNameField = value;
            }
        }
        
        /// <remarks/>
        public int Sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
            }
        }
        
        /// <remarks/>
        public int IndexNum {
            get {
                return this.indexNumField;
            }
            set {
                this.indexNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://index.bitauto.com/")]
    public partial class CitySortItem : IndexRegionSortItem {
        
        private int cityIdField;
        
        private string cityNameField;
        
        /// <remarks/>
        public int CityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
            }
        }
        
        /// <remarks/>
        public string cityName {
            get {
                return this.cityNameField;
            }
            set {
                this.cityNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://index.bitauto.com/")]
    public partial class IndexTrendItem {
        
        private DateObj indexDateField;
        
        private int indexNumField;
        
        private string dateTextField;
        
        private bool isVirtualField;
        
        private int rankField;
        
        /// <remarks/>
        public DateObj IndexDate {
            get {
                return this.indexDateField;
            }
            set {
                this.indexDateField = value;
            }
        }
        
        /// <remarks/>
        public int IndexNum {
            get {
                return this.indexNumField;
            }
            set {
                this.indexNumField = value;
            }
        }
        
        /// <remarks/>
        public string DateText {
            get {
                return this.dateTextField;
            }
            set {
                this.dateTextField = value;
            }
        }
        
        /// <remarks/>
        public bool isVirtual {
            get {
                return this.isVirtualField;
            }
            set {
                this.isVirtualField = value;
            }
        }
        
        /// <remarks/>
        public int Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://index.bitauto.com/")]
    public partial class IndexItem {
        
        private int idField;
        
        private string itmeNameField;
        
        private string itemUrlField;
        
        private int indexField;
        
        private int rankField;
        
        private string growthRateField;
        
        private string rankGrowthField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ItmeName {
            get {
                return this.itmeNameField;
            }
            set {
                this.itmeNameField = value;
            }
        }
        
        /// <remarks/>
        public string ItemUrl {
            get {
                return this.itemUrlField;
            }
            set {
                this.itemUrlField = value;
            }
        }
        
        /// <remarks/>
        public int Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        public int Rank {
            get {
                return this.rankField;
            }
            set {
                this.rankField = value;
            }
        }
        
        /// <remarks/>
        public string GrowthRate {
            get {
                return this.growthRateField;
            }
            set {
                this.growthRateField = value;
            }
        }
        
        /// <remarks/>
        public string RankGrowth {
            get {
                return this.rankGrowthField;
            }
            set {
                this.rankGrowthField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://index.bitauto.com/")]
    public enum RegionType {
        
        /// <remarks/>
        None,
        
        /// <remarks/>
        Province,
        
        /// <remarks/>
        City,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://index.bitauto.com/")]
    public enum BrandType {
        
        /// <remarks/>
        Producer,
        
        /// <remarks/>
        MasterBrand,
        
        /// <remarks/>
        Brand,
        
        /// <remarks/>
        Serial,
        
        /// <remarks/>
        Level,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLastDateCompletedEventHandler(object sender, GetLastDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DateObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DateObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetFirstDateCompletedEventHandler(object sender, GetFirstDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFirstDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFirstDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DateObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DateObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetShangPaiLastDateCompletedEventHandler(object sender, GetShangPaiLastDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShangPaiLastDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShangPaiLastDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DateObj Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DateObj)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetIndexTopListByLastDateCompletedEventHandler(object sender, GetIndexTopListByLastDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexTopListByLastDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexTopListByLastDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetIndexTopListCompletedEventHandler(object sender, GetIndexTopListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexTopListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexTopListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetIndexTopListProCompletedEventHandler(object sender, GetIndexTopListProCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexTopListProCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexTopListProCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCompareNear30DayTopListCompletedEventHandler(object sender, GetCompareNear30DayTopListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompareNear30DayTopListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompareNear30DayTopListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetIndexGrowthTopListCompletedEventHandler(object sender, GetIndexGrowthTopListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexGrowthTopListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexGrowthTopListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetIndexDataListByLastDateCompletedEventHandler(object sender, GetIndexDataListByLastDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexDataListByLastDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexDataListByLastDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IndexItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IndexItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetIndexDataListCompletedEventHandler(object sender, GetIndexDataListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexDataListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexDataListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IndexItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IndexItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRegionalIndexDataListCompletedEventHandler(object sender, GetRegionalIndexDataListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegionalIndexDataListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegionalIndexDataListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IndexItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IndexItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCompareNear30DaysIndexDataCompletedEventHandler(object sender, GetCompareNear30DaysIndexDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompareNear30DaysIndexDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompareNear30DaysIndexDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IndexItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IndexItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCompareIndexDataByLastDateCompletedEventHandler(object sender, GetCompareIndexDataByLastDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompareIndexDataByLastDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompareIndexDataByLastDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IndexItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IndexItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCompareIndexDataCompletedEventHandler(object sender, GetCompareIndexDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompareIndexDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompareIndexDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IndexItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IndexItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetIndexTrendDataCompletedEventHandler(object sender, GetIndexTrendDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIndexTrendDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIndexTrendDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRegionalIndexTrendDataCompletedEventHandler(object sender, GetRegionalIndexTrendDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegionalIndexTrendDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegionalIndexTrendDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IndexTrendItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IndexTrendItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCitySortListByLastDateCompletedEventHandler(object sender, GetCitySortListByLastDateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCitySortListByLastDateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCitySortListByLastDateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CitySortItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CitySortItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCitySortListCompletedEventHandler(object sender, GetCitySortListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCitySortListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCitySortListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CitySortItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CitySortItem[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetRegionSortListCompletedEventHandler(object sender, GetRegionSortListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRegionSortListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRegionSortListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IndexRegionSortItem[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IndexRegionSortItem[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591