//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitAuto.CarChannelAPI.Web.CarSourceForBitAuto {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="CarSourceForBitAuto.CarSourceForBitAutoSoap")]
    public interface CarSourceForBitAutoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="/GetCarSourceListByCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetCarSourceListByCity(int cityid, int countSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="/GetCarSourceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCarSourceList(int sid, int cityid, int countSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="/GetCarSourceListByByMoreRegulations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCarSourceListByByMoreRegulations(int sid, int cityid, int countSize, int orderType, int OrderDirection);
        
        [System.ServiceModel.OperationContractAttribute(Action="/GetDealerCarSourceList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetDealerCarSourceList(int bid, int cityid, int countSize, string productIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="/GetCarSourceListForBitAuto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode GetCarSourceListForBitAuto(int MainBrandId, int Branid, int SerialId, int cityid, int countSize);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarSourceForBitAutoSoapChannel : BitAuto.CarChannelAPI.Web.CarSourceForBitAuto.CarSourceForBitAutoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarSourceForBitAutoSoapClient : System.ServiceModel.ClientBase<BitAuto.CarChannelAPI.Web.CarSourceForBitAuto.CarSourceForBitAutoSoap>, BitAuto.CarChannelAPI.Web.CarSourceForBitAuto.CarSourceForBitAutoSoap {
        
        public CarSourceForBitAutoSoapClient() {
        }
        
        public CarSourceForBitAutoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarSourceForBitAutoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarSourceForBitAutoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarSourceForBitAutoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetCarSourceListByCity(int cityid, int countSize) {
            return base.Channel.GetCarSourceListByCity(cityid, countSize);
        }
        
        public System.Xml.XmlNode GetCarSourceList(int sid, int cityid, int countSize) {
            return base.Channel.GetCarSourceList(sid, cityid, countSize);
        }
        
        public System.Xml.XmlNode GetCarSourceListByByMoreRegulations(int sid, int cityid, int countSize, int orderType, int OrderDirection) {
            return base.Channel.GetCarSourceListByByMoreRegulations(sid, cityid, countSize, orderType, OrderDirection);
        }
        
        public System.Xml.XmlNode GetDealerCarSourceList(int bid, int cityid, int countSize, string productIds) {
            return base.Channel.GetDealerCarSourceList(bid, cityid, countSize, productIds);
        }
        
        public System.Xml.XmlNode GetCarSourceListForBitAuto(int MainBrandId, int Branid, int SerialId, int cityid, int countSize) {
            return base.Channel.GetCarSourceListForBitAuto(MainBrandId, Branid, SerialId, cityid, countSize);
        }
    }
}
